from plant_disease_model.analysis.plot_blocks.eradication_time_plot_block import EradicationTimePlotBlock
from plant_disease_model.analysis.plot_blocks.git_tag_plot_block import GitTagPlotBlock
from plant_disease_model.analysis.plot_blocks.model_illustration_plot_block import ModelIllustrationPlotBlock
from plant_disease_model.analysis.plot_blocks.sims_with_n_infected_nodes_vs_time import SimsWithNInfectedNodesPlotBlock
from plant_disease_model.analysis.plot_blocks.trained_performance_plot_block import TrainedPerformancePlotBlock
from plant_disease_model.analysis.plot_blocks.infected_culled_died_plot_block import InfectedCulledDiedPlotBlock
